name: Lokalise Pull
run-name: Pull from Lokalise [${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event.workflow_run.head_branch }}] ${{ github.event.after }}

on:
  workflow_dispatch:
    inputs:
      lokalise_token:
        description: 'Lokalise API token'
        required: true
      lokalise_project_id:
        description: 'Lokalise project ID'
        required: true
      github_token:
        description: 'GitHub token of the consuming project'
        required: true

jobs:
  retrieve-i18n:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Lokalise CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      - name: Pull translations from Lokalise
        env:
          LOKALISE_API_TOKEN: ${{ github.event.inputs.lokalise_token }}
          LOKALISE_PROJECT_ID: ${{ github.event.inputs.lokalise_project_id }}
        run: |
             ./bin/lokalise2 --token ${{ env.LOKALISE_API_TOKEN }} --project-id ${{ env.LOKALISE_PROJECT_ID }} file download --format yml --filter-langs=es_US --original-filenames=true --export-empty-as=skip --directory-prefix=/ --filter-data reviewed

      - name: Creates PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.event.inputs.github_token }}
          commit-message: '[Lokalise] New translation available'
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: lokalise-update
          branch-suffix: short-commit-hash
          delete-branch: true
          title: '[Lokalise] New translation available'
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
